
name: "tagged-release"

on:
  push:
    tags:
      - "v*" # for now take any tag

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: ubuntu-20.04
    container: alpine:latest

    steps:
      - uses: actions/checkout@v1
      - name: Install required dependencies
        shell: sh
        run: |
          apk update
          apk add mariadb mariadb-static mariadb-dev zlib-static openssl openssl-libs-static musl-dev git gcc make nim nimble upx

      - name: Install Nim dependencies
        shell: sh
        run: |
          cd databaseToToml
          nimble install -d -y

      - name: Build binary
        shell: sh
        run: |
          cd databaseToToml
          nimble muslBuild
          nim strip databaseToToml
          nim upx databaseToToml

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            databaseToToml/databaseToToml
